name: Build and Push

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * 1' # run at 3am every Monday
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: sqlmap

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Version SQLMap
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:test

      - name: Get SQLMap Version
        id: get_version
        run: |
          echo "version=$(docker run --rm ${{ env.DOCKER_IMAGE_NAME }}:test --version | cut -d '#' -f1)" >> $GITHUB_OUTPUT
          echo "prev_version=$(cat version.txt)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v4
        if: steps.get_version.outputs.version != steps.get_version.outputs.prev_version
        with:
          context: .
          push: true
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.get_version.outputs.version }}

      - name: Update Version
        if: steps.get_version.outputs.version != steps.get_version.outputs.prev_version
        run: |
          echo ${{ steps.get_version.outputs.version }}>version.txt
          git add version.txt
          git config user.name "Rob Emmerson"
          git config user.email "rob.emmerson@gmail.com"
          git commit -m "Updated version"
          git push
